services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hardpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=nothardpassword
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=nothardpassword
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
volumes:
  db_data:
  wordpress_data:
